version: 0.4.1-{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
install:
- ps: |
    Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/a65e3536-ad76-4808-9920-83702aeed082/3c6ab9eaa0bc99df442be91e7b7950ff/dotnet-sdk-3.0.100-preview7-012821-win-x64.exe'
    Start-Process .\dotnet-sdk-3.0.100-preview7-012821-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
before_build:
- cmd: nuget restore
build:
  project: Sakuno.SystemLayer.sln
  verbosity: minimal
after_test:
- ps: Move-Item artifacts\$env:configuration\*.nupkg $env:APPVEYOR_BUILD_FOLDER
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: T0e80U98+zD7uGDeVCUG3Y6WKYs850W8zvl6ETJq9QAnWfTSE1gRj7yLWMGfvJ6Z
  skip_symbols: true
