version: 0.4.1-{build}
image: Visual Studio 2019
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
nuget:
  disable_publish_on_pr: true
clone_depth: 10
init:
- git config --global core.autocrlf true
build_script:
- dotnet build -c Release
after_test:
- ps: Move-Item artifacts\Release\*.nupkg $env:APPVEYOR_BUILD_FOLDER
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: T0e80U98+zD7uGDeVCUG3Y6WKYs850W8zvl6ETJq9QAnWfTSE1gRj7yLWMGfvJ6Z
  skip_symbols: true
