version: 0.4-{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: Sakuno.SystemLayer.sln
  verbosity: minimal
after_test:
- ps: Move-Item artifacts\$env:configuration\*.nupkg .
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: T0e80U98+zD7uGDeVCUG3Y6WKYs850W8zvl6ETJq9QAnWfTSE1gRj7yLWMGfvJ6Z
  skip_symbols: true
